### ISSUE TITLE
Primitive interface updates 

### ISSUE THREAD

**Issue by kt474** [Qiskit/qiskit-ibm-runtime#1131]
Work should be done in the experimental [branch](https://github.com/Qiskit/qiskit-ibm-runtime/tree/experimental-0.2) 

- [ ] Update Estimator input/output
     - Details in [RFC 51](https://github.com/Qiskit/RFCs/pull/51), [RFC 53](https://github.com/Qiskit/RFCs/pull/53)
- [ ] Update Sampler input/output
     - Details in [RFC 56](https://github.com/Qiskit/RFCs/pull/56)
- [x] Update to OptionsV2 (Done) #1221, #1223 

Some the work regarding updating the Sampler and Estimator input/output has already been done (#1224). This work should be based off of https://github.com/Qiskit/qiskit/pull/11227 (Estimator) and https://github.com/Qiskit/qiskit/pull/11264 (Sampler)

The qiskit PRs has been split up into smaller ones

[Estimator 11227](https://github.com/Qiskit/qiskit/pull/11227):
- EstimatorV2 Container https://github.com/Qiskit/qiskit/pull/11524
- BaseEstimator V2 https://github.com/Qiskit/qiskit/pull/11527

[Sampler 11264](https://github.com/Qiskit/qiskit/pull/11264):
- SamplerV2 Container https://github.com/Qiskit/qiskit/pull/11542
- BaseSamplerV2 https://github.com/Qiskit/qiskit/pull/11529

**Comment by kt474** [comment]
Completed in `0.21.0` release
